services:
  claude-logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-logger-monolith
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - claude_logger_data:/app/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - API_SECRET=claude_api_secret_2024_change_me
      - MONGODB_URI=mongodb://admin:claude_logger_2024@localhost:27017/conversations?authSource=admin
      - REDIS_URL=redis://localhost:6379
      # Optional: Set TTL for automatic data expiration (in seconds)
      # - MONGODB_TTL_SECONDS=7776000  # 90 days (uncomment to enable)
      # By default, data persists indefinitely
      # Optional: Set Redis message limit (default: 5000)  
      # - REDIS_MESSAGE_LIMIT=5000     # 5000 messages (default)
      # - REDIS_MESSAGE_LIMIT=10000    # 10000 messages (more cache)
      # - REDIS_MESSAGE_LIMIT=1000     # 1000 messages (less memory)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  claude_logger_data:
    driver: local